import type { PermissionCode, SecurityClassification } from '@/lib/rbac/types';

export interface ModulePageDefinition {
  title: string;
  description: string;
  permission: PermissionCode;
  classification: SecurityClassification;
  actions: string[];
  stages: string[];
}

export const MODULE_PAGES: Record<string, ModulePageDefinition> = {
  '/dashboard/complaints': { title: 'Complaint Register', description: 'Register, triage and track complaints received by the Commission.', permission: 'complaints.view', classification: 'CONFIDENTIAL', actions: ['Register complaint', 'Open screening queue', 'Review referrals'], stages: ['Receipt & registration', 'Intake screening', 'Jurisdiction assessment', 'Decision / referral'] },
  '/dashboard/complaints/new': { title: 'New Complaint', description: 'Capture a new complaint with source, channel, subject body and initial confidentiality controls.', permission: 'complaints.create', classification: 'CONFIDENTIAL', actions: ['Create complaint', 'Attach intake documents'], stages: ['Receipt', 'Identity & contact', 'Issue summary', 'Initial classification'] },
  '/dashboard/complaints/referrals': { title: 'Complaint Referrals', description: 'Track matters referred to other competent authorities and evidence of referral.', permission: 'complaints.view', classification: 'CONFIDENTIAL', actions: ['Record referral', 'Review acknowledgement'], stages: ['Referral decision', 'Dispatch', 'Agency acknowledgement', 'Closure'] },
  '/dashboard/complaints/administrative': { title: 'Administrative Complaints', description: 'Manage complaints concerning administrative action and service delivery.', permission: 'complaints.view', classification: 'CONFIDENTIAL', actions: ['Open register', 'Assign screening'], stages: ['Screening', 'Preliminary inquiry', 'Investigation', 'Outcome'] },
  '/dashboard/complaints/human-rights': { title: 'Human Rights / Discrimination', description: 'Record and assess applicable rights and discrimination-related complaints within OCPNG jurisdiction.', permission: 'complaints.view', classification: 'CONFIDENTIAL', actions: ['Open register', 'Assess jurisdiction'], stages: ['Intake', 'Jurisdiction', 'Investigation', 'Outcome'] },
  '/dashboard/complaints/police': { title: 'Police Oversight', description: 'Track police-related oversight matters handled within the Commission’s lawful mandate.', permission: 'complaints.view', classification: 'CONFIDENTIAL', actions: ['Open register', 'Assign matter'], stages: ['Intake', 'Assessment', 'Investigation', 'Outcome'] },
  '/dashboard/intake': { title: 'Intake & Screening', description: 'Apply jurisdiction, admissibility, referral and priority screening controls.', permission: 'complaints.screen', classification: 'CONFIDENTIAL', actions: ['Screen next complaint', 'Record decision'], stages: ['Registration complete', 'Jurisdiction assessment', 'Screening decision', 'Assignment / exit'] },
  '/dashboard/investigations': { title: 'Investigations', description: 'Manage authorised preliminary and full investigations.', permission: 'investigations.view', classification: 'CONFIDENTIAL', actions: ['Open my cases', 'Start investigation plan'], stages: ['Preliminary investigation', 'Full investigation', 'Natural justice', 'Final assessment'] },
  '/dashboard/investigations/plans': { title: 'Investigation Plans', description: 'Define allegations, evidence tasks, interviews, notices and milestones before full investigation.', permission: 'investigations.manage', classification: 'CONFIDENTIAL', actions: ['Create plan', 'Review milestones'], stages: ['Scope', 'Allegations', 'Evidence plan', 'Approval'] },
  '/dashboard/investigations/evidence': { title: 'Evidence Register', description: 'Maintain evidence provenance, hashes, custody transfers and legal-hold status.', permission: 'evidence.manage', classification: 'CONFIDENTIAL', actions: ['Register evidence', 'Record custody event'], stages: ['Receipt', 'Hash / identify', 'Custody', 'Disposition / hold'] },
  '/dashboard/investigations/right-to-be-heard': { title: 'Right to be Heard', description: 'Record notices, service, response periods and responses before adverse findings.', permission: 'investigations.manage', classification: 'CONFIDENTIAL', actions: ['Issue notice', 'Record response'], stages: ['Draft adverse point', 'Notice', 'Response opportunity', 'Assessment'] },
  '/dashboard/investigations/findings': { title: 'Findings & Case Closure', description: 'Prepare supported findings, decision provenance and closure evidence.', permission: 'investigations.manage', classification: 'CONFIDENTIAL', actions: ['Prepare finding', 'Record closure'], stages: ['Draft findings', 'Review', 'Decision', 'Closure'] },
  '/dashboard/leadership': { title: 'Leader Registry', description: 'Protected registry supporting Leadership Code administration.', permission: 'leadership.view_restricted', classification: 'LEADERSHIP_RESTRICTED', actions: ['Open leader record', 'Review active matters'], stages: ['Registry', 'Initial assessment', 'Restricted case', 'Outcome'] },
  '/dashboard/leadership/investigations': { title: 'Leadership Investigations', description: 'Manage restricted Leadership Code investigations with natural-justice and Commission gates.', permission: 'leadership.manage', classification: 'LEADERSHIP_RESTRICTED', actions: ['Open investigation', 'Review counsel gate'], stages: ['Initial assessment', 'Investigation', 'Right to be Heard', 'Counsel review', 'Commission'] },
  '/dashboard/leadership/referrals': { title: 'Public Prosecutor Referrals', description: 'Record authorised referrals and associated decision provenance.', permission: 'leadership.manage', classification: 'LEADERSHIP_RESTRICTED', actions: ['Prepare referral', 'Track acknowledgement'], stages: ['Commission decision', 'Referral pack', 'Dispatch', 'Tracking'] },
  '/dashboard/leadership/tribunals': { title: 'Tribunal Matters', description: 'Track tribunal matters and final outcomes after authorised referral.', permission: 'leadership.manage', classification: 'LEADERSHIP_RESTRICTED', actions: ['Open tribunal register', 'Record event'], stages: ['Referral', 'Tribunal tracking', 'Outcome', 'Closure'] },
  '/dashboard/annual-statements': { title: 'Annual Statements', description: 'Administer leader statement periods, submissions, validation and protected declarations.', permission: 'annual_statements.view_secret', classification: 'ANNUAL_STATEMENT_SECRET', actions: ['Open statement period', 'Review submissions'], stages: ['Period open', 'Issued', 'Submitted / late', 'Validation', 'Compliance outcome'] },
  '/dashboard/annual-statements/variance-review': { title: 'Variance & Anomaly Review', description: 'Compare declaration periods and flag material changes for human review; flags are not findings of misconduct.', permission: 'annual_statements.manage', classification: 'ANNUAL_STATEMENT_SECRET', actions: ['Review variance', 'Request explanation'], stages: ['Comparative review', 'Variance flag', 'Explanation request', 'Assessment'] },
  '/dashboard/government-bodies': { title: 'Government Bodies Registry', description: 'Maintain public-body profiles, liaison points and oversight history.', permission: 'oversight.view', classification: 'INTERNAL', actions: ['Open body register', 'Review liaison officers'], stages: ['Registry', 'Liaison', 'Monitoring', 'Follow-up'] },
  '/dashboard/oversight': { title: 'Monitoring & Evaluation', description: 'Plan and record government-body monitoring, service-delivery reviews and systemic oversight.', permission: 'oversight.view', classification: 'CONFIDENTIAL', actions: ['Create monitoring activity', 'Review indicators'], stages: ['Plan', 'Monitor', 'Assess', 'Follow-up'] },
  '/dashboard/oversight/inspections': { title: 'Inspections', description: 'Plan inspections and record evidence-based inspection findings.', permission: 'oversight.manage', classification: 'CONFIDENTIAL', actions: ['Schedule inspection', 'Record finding'], stages: ['Authority', 'Plan', 'Inspection', 'Finding', 'Follow-up'] },
  '/dashboard/oversight/systemic-issues': { title: 'Systemic Issues / Own Motion', description: 'Manage authorised systemic and own-motion investigations.', permission: 'oversight.manage', classification: 'CONFIDENTIAL', actions: ['Register issue', 'Prepare own-motion assessment'], stages: ['Signal', 'Authorisation', 'Investigation', 'Recommendation'] },
  '/dashboard/compliance': { title: 'Recommendations', description: 'Track recommendations issued by the Commission and agency response status.', permission: 'compliance.view', classification: 'CONFIDENTIAL', actions: ['Open register', 'Review due responses'], stages: ['Issued', 'Response due', 'Agency response', 'Review'] },
  '/dashboard/compliance/actions': { title: 'Corrective Actions', description: 'Track corrective action plans and evidence of implementation.', permission: 'compliance.manage', classification: 'CONFIDENTIAL', actions: ['Record action', 'Attach evidence'], stages: ['Action plan', 'Evidence', 'Compliance review', 'Outcome'] },
  '/dashboard/compliance/escalations': { title: 'Overdue & Escalations', description: 'Surface overdue responses and approved escalation actions.', permission: 'compliance.manage', classification: 'CONFIDENTIAL', actions: ['Review overdue', 'Record escalation'], stages: ['Overdue', 'Escalation', 'Response', 'Closure'] },
  '/dashboard/commission': { title: 'Members of Commission', description: 'Prepare meetings, agendas and restricted submissions for Members of Commission.', permission: 'commission.view', classification: 'RESTRICTED', actions: ['Create meeting', 'Prepare submission'], stages: ['Meeting', 'Agenda', 'Submission', 'Deliberation'] },
  '/dashboard/commission/decisions': { title: 'Commission Decisions & Actions', description: 'Record decisions actually made by Members of Commission; the system never infers a decision.', permission: 'commission.record_decision', classification: 'RESTRICTED', actions: ['Record decision', 'Assign action'], stages: ['Decision capture', 'Version lock', 'Action assignment', 'Audit'] },
  '/dashboard/legal': { title: 'Legal Matters', description: 'Manage legally privileged advice, references and related matters.', permission: 'legal.view_privileged', classification: 'LEGAL_PRIVILEGE', actions: ['Open legal matter', 'Review deadlines'], stages: ['Instruction', 'Advice', 'Action', 'Closure'] },
  '/dashboard/legal/matters': { title: 'Constitutional / Litigation / Tribunal', description: 'Track constitutional references, litigation, legislative review and tribunal events.', permission: 'legal.manage', classification: 'LEGAL_PRIVILEGE', actions: ['Record event', 'Open reference'], stages: ['Matter opened', 'Event tracking', 'Legal review', 'Outcome'] },
  '/dashboard/intelligence': { title: 'Intelligence Reports', description: 'Protected intelligence register for authorised information and assessments.', permission: 'intelligence.view_secret', classification: 'INTELLIGENCE_SECRET', actions: ['Open intelligence register', 'Create draft report'], stages: ['Receive', 'Assess', 'Link', 'Disseminate'] },
  '/dashboard/intelligence/analysis': { title: 'Sources / Entities / Analysis', description: 'Maintain protected source, entity and relationship analysis.', permission: 'intelligence.manage', classification: 'INTELLIGENCE_SECRET', actions: ['Review entities', 'Link intelligence'], stages: ['Source handling', 'Entity resolution', 'Analysis', 'Controlled dissemination'] },
  '/dashboard/reports': { title: 'Management & Statutory Reports', description: 'Generate scoped management, operational and statutory reporting from authorised records.', permission: 'reports.view', classification: 'INTERNAL', actions: ['Executive report', 'Complaint statistics', 'Compliance report'], stages: ['Select scope', 'Validate data', 'Generate', 'Audit export'] },
  '/dashboard/tasks': { title: 'My Work', description: 'View assigned statutory and operational workflow tasks.', permission: 'tasks.view', classification: 'INTERNAL', actions: ['Open priority task', 'Review due dates'], stages: ['Assigned', 'In progress', 'Review', 'Complete'] },
  '/dashboard/notifications': { title: 'Alerts / Overdue Actions', description: 'View alerts, approaching deadlines and overdue authorised actions.', permission: 'notifications.view', classification: 'INTERNAL', actions: ['Review alerts', 'Open related matter'], stages: ['New', 'Acknowledged', 'Actioned'] },
  '/dashboard/users': { title: 'User Administration', description: 'Manage user identity, status and organisational assignment without protected-record bypass.', permission: 'admin.manage_users', classification: 'INTERNAL', actions: ['Create user', 'Review assignments'], stages: ['Identity', 'Organisation', 'Roles', 'Activation'] },
  '/dashboard/users/roles': { title: 'Roles, Permissions & Compartments', description: 'Configure functional roles and need-to-know compartments under controlled administration.', permission: 'admin.manage_roles', classification: 'INTERNAL', actions: ['Review roles', 'Grant compartment'], stages: ['Role', 'Permission', 'Scope', 'Compartment'] },
  '/dashboard/audit-log': { title: 'Audit Logs', description: 'Review immutable security, access, export, role and decision events.', permission: 'audit.view', classification: 'RESTRICTED', actions: ['Search audit log', 'Review privileged event'], stages: ['Capture', 'Protect', 'Review', 'Export with authority'] },
  '/dashboard/settings': { title: 'System Settings', description: 'Manage approved master data and system configuration.', permission: 'admin.manage_settings', classification: 'INTERNAL', actions: ['Review settings', 'Manage master data'], stages: ['Draft change', 'Approve', 'Apply', 'Audit'] },
};

export function getModulePage(pathname: string): ModulePageDefinition {
  const page = MODULE_PAGES[pathname];
  if (!page) throw new Error(`Unknown OCPNG module page: ${pathname}`);
  return page;
}
