-- RLS, RBAC, data-scope, compartment and append-only audit controls
create or replace function public.has_permission(permission_code text) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.user_roles ur join public.role_permissions rp on rp.role_id=ur.role_id join public.permissions p on p.id=rp.permission_id where ur.user_id=auth.uid() and p.code=permission_code); $$;
create or replace function public.has_compartment(classification_code text) returns boolean language sql stable security definer set search_path='' as $$ select classification_code in ('PUBLIC','INTERNAL') or exists(select 1 from public.user_compartments uc join public.security_compartments sc on sc.id=uc.compartment_id where uc.user_id=auth.uid() and sc.code::text=classification_code); $$;
create or replace function public.has_scope(scope_code text) returns boolean language sql stable security definer set search_path='' as $$ select scope_code is null or exists(select 1 from public.data_scopes ds where ds.user_id=auth.uid() and ds.active and (ds.scope_code=scope_code or ds.scope_code='*')); $$;
create or replace function public.can_access_case(target_case_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select target_case_id is null or exists(select 1 from public.cases c where c.id=target_case_id and (c.responsible_officer_id=auth.uid() or exists(select 1 from public.case_assignments ca where ca.case_ref=c.id and ca.user_id=auth.uid() and ca.ended_at is null))); $$;
create or replace function public.record_access_allowed(classification_code text, scope_code text, target_case_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and public.has_compartment(classification_code) and public.has_scope(scope_code) and (target_case_id is null or public.can_access_case(target_case_id)); $$;
create or replace function public.prevent_audit_mutation() returns trigger language plpgsql security definer set search_path='' as $$ begin raise exception 'audit_events is append-only'; end; $$;
create trigger audit_events_append_only before update or delete on public.audit_events for each row execute function public.prevent_audit_mutation();
alter table public.profiles enable row level security;
alter table public.roles enable row level security;
alter table public.permissions enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;
alter table public.data_scopes enable row level security;
alter table public.security_compartments enable row level security;
alter table public.user_compartments enable row level security;
alter table public.divisions enable row level security;
alter table public.units enable row level security;
alter table public.teams enable row level security;
alter table public.positions enable row level security;
alter table public.officer_assignments enable row level security;
alter table public.people enable row level security;
alter table public.leaders enable row level security;
alter table public.leader_positions enable row level security;
alter table public.government_bodies enable row level security;
alter table public.government_body_contacts enable row level security;
alter table public.liaison_officers enable row level security;
alter table public.complaints enable row level security;
alter table public.complaint_parties enable row level security;
alter table public.complaint_documents enable row level security;
alter table public.screening_assessments enable row level security;
alter table public.screening_decisions enable row level security;
alter table public.cases enable row level security;
alter table public.case_assignments enable row level security;
alter table public.case_parties enable row level security;
alter table public.case_events enable row level security;
alter table public.case_tasks enable row level security;
alter table public.case_extensions enable row level security;
alter table public.allegations enable row level security;
alter table public.investigations enable row level security;
alter table public.investigation_plans enable row level security;
alter table public.investigation_plan_steps enable row level security;
alter table public.evidence_items enable row level security;
alter table public.evidence_custody_events enable row level security;
alter table public.interviews enable row level security;
alter table public.interview_participants enable row level security;
alter table public.statutory_notices enable row level security;
alter table public.information_requests enable row level security;
alter table public.responses enable row level security;
alter table public.findings enable row level security;
alter table public.right_to_be_heard_notices enable row level security;
alter table public.right_to_be_heard_responses enable row level security;
alter table public.closure_decisions enable row level security;
alter table public.annual_statements enable row level security;
alter table public.annual_statement_periods enable row level security;
alter table public.annual_statement_reminders enable row level security;
alter table public.annual_statement_breach_notices enable row level security;
alter table public.assets enable row level security;
alter table public.liabilities enable row level security;
alter table public.income_sources enable row level security;
alter table public.business_interests enable row level security;
alter table public.directorships enable row level security;
alter table public.shareholdings enable row level security;
alter table public.gifts enable row level security;
alter table public.financial_transactions enable row level security;
alter table public.declaration_variances enable row level security;
alter table public.explanation_requests enable row level security;
alter table public.explanation_responses enable row level security;
alter table public.recommendations enable row level security;
alter table public.recommendation_recipients enable row level security;
alter table public.agency_responses enable row level security;
alter table public.compliance_actions enable row level security;
alter table public.compliance_evidence enable row level security;
alter table public.compliance_reviews enable row level security;
alter table public.escalations enable row level security;
alter table public.moc_meetings enable row level security;
alter table public.moc_agenda_items enable row level security;
alter table public.moc_submissions enable row level security;
alter table public.moc_decisions enable row level security;
alter table public.moc_actions enable row level security;
alter table public.delegations enable row level security;
alter table public.legal_matters enable row level security;
alter table public.constitutional_references enable row level security;
alter table public.litigation_events enable row level security;
alter table public.legislative_reviews enable row level security;
alter table public.public_prosecutor_referrals enable row level security;
alter table public.tribunal_matters enable row level security;
alter table public.monitoring_programs enable row level security;
alter table public.monitoring_activities enable row level security;
alter table public.inspections enable row level security;
alter table public.inspection_findings enable row level security;
alter table public.service_delivery_indicators enable row level security;
alter table public.systemic_issues enable row level security;
alter table public.intelligence_reports enable row level security;
alter table public.intelligence_sources enable row level security;
alter table public.intelligence_entities enable row level security;
alter table public.intelligence_links enable row level security;
alter table public.documents enable row level security;
alter table public.document_versions enable row level security;
alter table public.notifications enable row level security;
alter table public.workflow_tasks enable row level security;
alter table public.audit_events enable row level security;
alter table public.export_events enable row level security;
alter table public.system_settings enable row level security;
create policy profiles_select on public.profiles for select to authenticated using (id=auth.uid() or public.has_permission('admin.manage_users'));
do $policy$ declare item record; begin for item in select * from jsonb_each_text('{"roles":"admin.manage_roles","permissions":"admin.manage_roles","user_roles":"admin.manage_roles","role_permissions":"admin.manage_roles","data_scopes":"admin.manage_users","security_compartments":"admin.manage_roles","user_compartments":"admin.manage_roles","divisions":"admin.manage_users","units":"admin.manage_users","teams":"admin.manage_users","positions":"admin.manage_users","officer_assignments":"admin.manage_users","people":"admin.manage_users","leaders":"leadership.view_restricted","leader_positions":"leadership.view_restricted","government_bodies":"oversight.view","government_body_contacts":"oversight.view","liaison_officers":"oversight.view","complaints":"complaints.view","complaint_parties":"complaints.view","complaint_documents":"complaints.view","screening_assessments":"complaints.screen","screening_decisions":"complaints.screen","cases":"investigations.view","case_assignments":"investigations.view","case_parties":"investigations.view","case_events":"investigations.view","case_tasks":"investigations.view","case_extensions":"investigations.view","allegations":"investigations.view","investigations":"investigations.view","investigation_plans":"investigations.view","investigation_plan_steps":"investigations.view","evidence_items":"evidence.manage","evidence_custody_events":"evidence.manage","interviews":"investigations.view","interview_participants":"investigations.view","statutory_notices":"investigations.view","information_requests":"investigations.view","responses":"investigations.view","findings":"investigations.view","right_to_be_heard_notices":"investigations.view","right_to_be_heard_responses":"investigations.view","closure_decisions":"investigations.view","annual_statements":"annual_statements.view_secret","annual_statement_periods":"annual_statements.view_secret","annual_statement_reminders":"annual_statements.view_secret","annual_statement_breach_notices":"annual_statements.view_secret","assets":"annual_statements.view_secret","liabilities":"annual_statements.view_secret","income_sources":"annual_statements.view_secret","business_interests":"annual_statements.view_secret","directorships":"annual_statements.view_secret","shareholdings":"annual_statements.view_secret","gifts":"annual_statements.view_secret","financial_transactions":"annual_statements.view_secret","declaration_variances":"annual_statements.view_secret","explanation_requests":"annual_statements.view_secret","explanation_responses":"annual_statements.view_secret","recommendations":"compliance.view","recommendation_recipients":"compliance.view","agency_responses":"compliance.view","compliance_actions":"compliance.view","compliance_evidence":"compliance.view","compliance_reviews":"compliance.view","escalations":"compliance.view","moc_meetings":"commission.view","moc_agenda_items":"commission.view","moc_submissions":"commission.view","moc_decisions":"commission.view","moc_actions":"commission.view","delegations":"commission.view","legal_matters":"legal.view_privileged","constitutional_references":"legal.view_privileged","litigation_events":"legal.view_privileged","legislative_reviews":"legal.view_privileged","public_prosecutor_referrals":"legal.view_privileged","tribunal_matters":"legal.view_privileged","monitoring_programs":"oversight.view","monitoring_activities":"oversight.view","inspections":"oversight.view","inspection_findings":"oversight.view","service_delivery_indicators":"oversight.view","systemic_issues":"oversight.view","intelligence_reports":"intelligence.view_secret","intelligence_sources":"intelligence.view_secret","intelligence_entities":"intelligence.view_secret","intelligence_links":"intelligence.view_secret","documents":"reports.view","document_versions":"reports.view","export_events":"reports.view","notifications":"notifications.view","workflow_tasks":"tasks.view","audit_events":"audit.view","system_settings":"admin.manage_settings"}'::jsonb) loop execute format('create policy %I_select on public.%I for select to authenticated using (public.has_permission(%L) and public.record_access_allowed(classification::text,organisation_scope,case_id))', item.key,item.key,item.value); end loop; end $policy$;
create policy audit_events_insert on public.audit_events for insert to authenticated with check (auth.uid() is not null); -- append-only
