-- Leadership Code and Annual Statements
create table if not exists public.annual_statement_periods (id uuid primary key default gen_random_uuid(), name text not null, opens_on date not null, due_on date not null, closes_on date, status text not null default 'planned', classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text default 'leadership', case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.annual_statements (id uuid primary key default gen_random_uuid(), leader_id uuid not null references public.leaders(id), period_id uuid not null references public.annual_statement_periods(id), status text not null, submitted_at timestamptz, validated_at timestamptz, classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text default 'leadership', case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(leader_id,period_id));
create table if not exists public.annual_statement_reminders (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.annual_statement_breach_notices (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.assets (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.liabilities (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.income_sources (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.business_interests (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.directorships (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.shareholdings (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.gifts (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.financial_transactions (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.declaration_variances (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.explanation_requests (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.explanation_responses (id uuid primary key default gen_random_uuid(), annual_statement_id uuid references public.annual_statements(id), classification public.security_classification not null default 'ANNUAL_STATEMENT_SECRET', organisation_scope text, case_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
